#include "tuiide/ui_localization.hpp"

#include <unordered_map>

namespace tuiide {

auto localizedUiText(std::string_view language, std::string_view english) -> std::string {
  if (language != "ru") return std::string(english);
  // Ключи совпадают с исходными подписями Final Cut; & обозначает mnemonic.
  static const std::unordered_map<std::string_view, std::string_view> russian{
    {"&File", "&Файл"}, {"&Edit", "&Правка"}, {"&Search", "П&оиск"},
    {"&Run", "&Запуск"}, {"&Project", "Про&ект"}, {"&Debug", "&Отладка"},
    {"&Tools", "&Сервис"}, {"&Window", "О&кно"}, {"&Help", "С&правка"},
    {"&Tests", "&Тесты"},
    {"New &Project...", "Новый &проект..."},
    {"&Open Project...", "&Открыть проект..."},
    {"Recent P&rojects...", "Недавние про&екты..."},
    {"Close Pro&ject", "&Закрыть проект"},
    {"&New", "&Новый файл"}, {"New from &template...", "Из &шаблона..."},
    {"Open f&ile...", "Открыть &файл..."}, {"Recent &Files", "Недавние &файлы"},
    {"&Save", "&Сохранить"}, {"Save A&ll", "Сохранить &все"},
    {"Save &As...", "Сохранить &как..."}, {"&Close", "&Закрыть"},
    {"Close Ot&hers", "Закрыть &остальные"}, {"Clos&e All", "Закрыть в&се"},
    {"Reopen Close&d", "Открыть закры&тый"}, {"E&xit", "В&ыход"},
    {"&Undo", "&Отменить"}, {"&Redo", "&Повторить"}, {"Cu&t", "Выреза&ть"},
    {"&Copy", "&Копировать"}, {"&Paste", "&Вставить"},
    {"Select &All", "Выделить &всё"}, {"Toggle co&mment", "Переключить ко&мментарий"},
    {"Duplicate l&ine", "Дублировать &строку"}, {"Move li&ne up", "Строку в&верх"},
    {"Move line do&wn", "Строку вни&з"}, {"De&lete line", "&Удалить строку"},
    {"&Find...", "&Найти..."}, {"Find &next", "Следу&ющее совпадение"},
    {"Find &previous", "Пре&дыдущее совпадение"}, {"&Replace...", "&Заменить..."},
    {"Find in pro&ject...", "Найти в про&екте..."}, {"&Go to line...", "&Перейти к строке..."},
    {"Go to &definition", "К &определению"}, {"Find r&eferences", "Найти &ссылки"},
    {"Pro&blems...", "Пр&облемы..."}, {"Next d&iagnostic", "Следующая &диагностика"},
    {"C&onfigure", "&Настроить"}, {"&Build", "&Собрать"},
    {"&Rebuild", "Пере&собрать"}, {"C&lean", "О&чистить"},
    {"Cancel B&uild", "Отменить сбо&рку"}, {"Ru&n", "За&пустить"},
    {"Stop progra&m", "Остановить програ&мму"},
    {"Select &active configuration...", "Выбрать &конфигурацию..."},
    {"Manage &Debug/Run configurations...", "Настроить запуск и &отладку..."},
    {"Configure &preset...", "Пресет &конфигурации..."},
    {"Build pre&set...", "Пресет сбо&рки..."}, {"Select tar&get...", "Выбрать &цель..."},
    {"&Discover tests", "&Найти тесты"}, {"Run &all tests", "Запустить &все тесты"},
    {"Run &selected test", "Запустить &выбранный тест"},
    {"Rerun &failed tests", "Повторить &упавшие тесты"},
    {"Test &preset...", "&Пресет тестов..."}, {"S&top tests", "Ос&тановить тесты"},
    {"&Refresh tree", "&Обновить дерево"}, {"&Filter...", "&Фильтр..."},
    {"&Clear filter", "С&бросить фильтр"}, {"New &directory...", "Новый &каталог..."},
    {"Rename / &Move...", "Переименовать / &переместить..."},
    {"Delete director&y", "Удалить катало&г"},
    {"&Start / Continue", "&Старт / продолжить"}, {"Pa&use", "Пау&за"},
    {"S&top", "Ос&тановить"}, {"&Restart", "&Перезапустить"},
    {"Attach to process...", "Подключиться к процессу..."},
    {"Open &core dump...", "Открыть &дамп памяти..."},
    {"Toggle &breakpoint", "Переключить &точку останова"},
    {"Breakpoint &properties...", "&Свойства точки останова..."},
    {"Enable / &disable breakpoint", "Включить / &выключить точку"},
    {"Remove brea&kpoint", "Удалить то&чку"},
    {"Remove &all breakpoints", "Удалить &все точки"},
    {"&Next", "&Следующий шаг"}, {"Step &into", "Шаг &внутрь"},
    {"Step &out", "Шаг &наружу"}, {"Add &watch...", "Добавить &наблюдение..."},
    {"&Evaluate expression...", "&Вычислить выражение..."},
    {"Set &variable value...", "Изменить &переменную..."},
    {"Disassembl&y...", "&Дизассемблирование..."}, {"&Memory...", "&Память..."},
    {"Toggle re&gisters", "Переключить &регистры"},
    {"Signal &handling...", "Обработка &сигналов..."},
    {"Co&mpletion", "Автодо&полнение"}, {"Signature &help...", "Подсказка &сигнатуры..."},
    {"Symbol &information", "Сведения о &символе"},
    {"&Rename symbol...", "&Переименовать символ..."},
    {"Code &actions...", "&Действия с кодом..."},
    {"Organize incl&udes", "Упорядочить &include"},
    {"Switch header / &source", "Переключить заголовок / &исходник"},
    {"&Workspace symbols...", "&Символы проекта..."},
    {"Ca&ll hierarchy...", "Иерархия &вызовов..."},
    {"Type hierarch&y...", "Иерархия &типов..."},
    {"Format &document", "Форматировать &документ"},
    {"Format selectio&n", "Форматировать в&ыделение"},
    {"Toolchain &kits...", "Наборы &инструментов..."},
    {"Language insights...", "Сведения о языке..."},
    {"Run analysis / profil&e...", "Запустить анализ / профилирование..."},
    {"Stop analysis acti&vity", "Остановить &анализ"},
    {"Command &palette...", "Палитра &команд..."},
    {"Configure sh&ortcut...", "Настроить &сочетание..."},
    {"Shortcut con&flicts...", "Конфликты &сочетаний..."},
    {"Editor &theme...", "&Тема редактора..."},
    {"Editor &colors...", "&Цвета редактора..."},
    {"Project settin&gs...", "Настройки &проекта..."},
    {"Interface language", "Язык интерфейса"},
    {"&Previous file", "&Предыдущий файл"}, {"&Next file", "&Следующий файл"},
    {"Show Open &files", "Показать открытые &файлы"},
    {"Show pr&oject", "Показать про&ект"}, {"Show O&utline", "Показать структуру"},
    {"Show &Debug", "Показать &отладку"},
    {"Show &Breakpoints", "Показать точки &останова"},
    {"Show T&ests", "Показать &тесты"}, {"Show &Git", "Показать &Git"},
    {"&Clear active lower panel", "&Очистить нижнюю панель"},
    {"Cop&y active lower panel", "&Копировать нижнюю панель"},
    {"Filter proble&ms...", "Фильтр пробле&м..."},
    {"Sidebar n&arrower", "Сделать боковую панель у&же"},
    {"Sidebar &wider", "Сделать боковую панель &шире"},
    {"Lower panel &shorter", "У&меньшить нижнюю панель"},
    {"Lower panel &taller", "У&величить нижнюю панель"},
    {"&Reset panel sizes", "&Сбросить размеры панелей"},
    {"&Keyboard shortcuts", "&Горячие клавиши"},
    {"&About TUI IDE", "&О TUI IDE"},
    {"Open files", "Открытые файлы"}, {"Project", "Проект"},
    {"Outline", "Структура"}, {"Debug", "Отладка"},
    {"Breakpoints", "Точки останова"}, {"Tests", "Тесты"},
    {"Output", "Вывод"}, {"Problems", "Проблемы"},
    {"Build", "Сборка"}, {"Terminal", "Терминал"},
    {"Analysis", "Анализ"}, {"Build output", "Вывод сборки"},
    {"Analysis output", "Вывод анализа"}, {"No problems", "Проблем нет"},
    {"Open a directory containing CMakeLists.txt", "Открыть каталог с CMakeLists.txt"},
    {"Open a recently used CMake project", "Открыть недавний проект CMake"},
    {"Close the current project", "Закрыть текущий проект"},
    {"Create a new source file", "Создать новый исходный файл"},
    {"Create a C/C++ file or class and add it to CMake",
      "Создать файл или класс C/C++ и добавить в CMake"},
    {"Open a C or C++ source file", "Открыть исходный файл C или C++"},
    {"Open or clear the persistent file history", "Открыть или очистить историю файлов"},
    {"(History is empty)", "(История пуста)"}, {"&Clear history", "&Очистить историю"},
    {"Remove all entries from Recent Files", "Удалить все записи из недавних файлов"},
    {"Open ", "Открыть "},
    {"Save the active source file", "Сохранить активный исходный файл"},
    {"Save every modified document", "Сохранить все изменённые документы"},
    {"Save the active file under another name", "Сохранить активный файл под другим именем"},
    {"Close the active file", "Закрыть активный файл"},
    {"Close every file except the active one", "Закрыть все файлы кроме активного"},
    {"Close every open file", "Закрыть все открытые файлы"},
    {"Reopen the most recently closed saved file", "Открыть последний закрытый сохранённый файл"},
    {"Exit TUI IDE", "Выйти из TUI IDE"},
    {"Undo the last edit", "Отменить последнее изменение"},
    {"Redo the last edit", "Повторить последнее изменение"},
    {"Cut selection to the system clipboard", "Вырезать выделение в системный буфер"},
    {"Copy selection to the system clipboard", "Скопировать выделение в системный буфер"},
    {"Paste from the system clipboard", "Вставить из системного буфера"},
    {"Select the entire document", "Выделить весь документ"},
    {"Comment or uncomment the selected lines", "Закомментировать или раскомментировать строки"},
    {"Duplicate the current line or selected lines", "Дублировать текущую строку или выделение"},
    {"Move the current line or selected lines up", "Переместить текущую строку или выделение вверх"},
    {"Move the current line or selected lines down", "Переместить текущую строку или выделение вниз"},
    {"Delete the current line or selected lines", "Удалить текущую строку или выделение"},
    {"Find text in the active file", "Найти текст в активном файле"},
    {"Find the next match using the current options", "Найти следующее совпадение с текущими параметрами"},
    {"Find the previous match using the current options", "Найти предыдущее совпадение с текущими параметрами"},
    {"Find and replace text in a file or project", "Найти и заменить текст в файле или проекте"},
    {"Search across editable project files", "Искать по редактируемым файлам проекта"},
    {"Move to a line number", "Перейти к номеру строки"},
    {"Open the symbol definition", "Открыть определение символа"},
    {"List symbol references", "Показать ссылки на символ"},
    {"List build and clangd problems", "Показать проблемы сборки и clangd"},
    {"Open the next build or clangd diagnostic", "Открыть следующую диагностику сборки или clangd"},
    {"Configure the project with CMake", "Настроить проект через CMake"},
    {"Build the project; configure first when required", "Собрать проект; при необходимости сначала настроить"},
    {"Clean and build the project", "Очистить и собрать проект"},
    {"Build the CMake clean target", "Собрать цель clean CMake"},
    {"Stop the active CMake operation", "Остановить текущую операцию CMake"},
    {"Run the selected executable", "Запустить выбранный исполняемый файл"},
    {"Terminate the running program and its process group", "Завершить программу и её группу процессов"},
    {"Quickly select the active Run/Debug configuration", "Быстро выбрать активную конфигурацию запуска/отладки"},
    {"Create, clone, edit, delete, or select Run/Debug configurations",
      "Создать, копировать, изменить, удалить или выбрать конфигурации запуска/отладки"},
    {"Select a CMake configure preset", "Выбрать пресет настройки CMake"},
    {"Select a CMake build preset", "Выбрать пресет сборки CMake"},
    {"Select an executable CMake target", "Выбрать исполняемую цель CMake"},
    {"Discover tests using CTest JSON output", "Найти тесты через JSON-вывод CTest"},
    {"Run all discovered CTest tests", "Запустить все найденные тесты CTest"},
    {"Run the test selected in the Tests panel", "Запустить тест, выбранный в панели Tests"},
    {"Rerun tests from CTest's failed-test log", "Повторить тесты из журнала упавших CTest"},
    {"Select and run a CMake test preset", "Выбрать и запустить тестовый пресет CMake"},
    {"Stop the active CTest process", "Остановить текущий процесс CTest"},
    {"Start or continue debugging", "Начать или продолжить отладку"},
    {"Pause the debuggee", "Приостановить отлаживаемую программу"},
    {"Stop the debug session and terminate GDB", "Остановить сессию отладки и завершить GDB"},
    {"Restart the selected executable under GDB", "Перезапустить выбранный исполняемый файл под GDB"},
    {"Attach GDB to a running Linux process", "Подключить GDB к запущенному процессу Linux"},
    {"Open an executable and core dump for read-only inspection",
      "Открыть исполняемый файл и core dump только для просмотра"},
    {"Toggle breakpoint on the current line", "Переключить точку останова на текущей строке"},
    {"Edit condition, ignored hits, or logpoint message", "Изменить условие, пропуски или сообщение logpoint"},
    {"Enable or disable the selected breakpoint", "Включить или выключить выбранную точку останова"},
    {"Remove the selected breakpoint", "Удалить выбранную точку останова"},
    {"Remove every project breakpoint", "Удалить все точки останова проекта"},
    {"Step over the current source line", "Выполнить текущую строку без входа в вызовы"},
    {"Step into the current call", "Войти в текущий вызов"},
    {"Finish the current stack frame", "Завершить текущий кадр стека"},
    {"Add a GDB watch expression", "Добавить выражение наблюдения GDB"},
    {"Evaluate a C/C++ expression in the selected stack frame",
      "Вычислить выражение C/C++ в выбранном кадре стека"},
    {"Change a variable in the selected stack frame", "Изменить переменную в выбранном кадре стека"},
    {"Disassemble machine instructions near an address or $pc",
      "Показать инструкции рядом с адресом или $pc"},
    {"Read a bounded memory range as hex and ASCII", "Прочитать ограниченный диапазон памяти как hex и ASCII"},
    {"Show or hide amd64 registers", "Показать или скрыть регистры amd64"},
    {"Inspect signal policies, configure handling, or send a signal and continue",
      "Просмотреть политики сигналов, настроить обработку или отправить сигнал"},
    {"Request clangd completion", "Запросить автодополнение clangd"},
    {"Show clangd function signature help", "Показать подсказку сигнатуры clangd"},
    {"Show clangd symbol information", "Показать сведения о символе clangd"},
    {"Rename a symbol across the workspace", "Переименовать символ во всём рабочем пространстве"},
    {"Show clangd quick fixes and refactorings", "Показать быстрые исправления и рефакторинги clangd"},
    {"Sort and remove unused includes with clangd", "Отсортировать и удалить неиспользуемые include через clangd"},
    {"Switch between matching C/C++ header and source files",
      "Переключиться между связанными заголовком и исходником C/C++"},
    {"Search symbols across the clangd workspace index", "Искать символы в индексе рабочего пространства clangd"},
    {"Show incoming and outgoing calls for the symbol at the cursor",
      "Показать входящие и исходящие вызовы для символа под курсором"},
    {"Show supertypes and subtypes for the type at the cursor",
      "Показать базовые и производные типы для типа под курсором"},
    {"Format the active C/C++ document with clang-format",
      "Форматировать активный документ C/C++ через clang-format"},
    {"Format selected C/C++ lines with clang-format",
      "Форматировать выделенные строки C/C++ через clang-format"},
    {"Detect and select a C/C++ toolchain kit", "Найти и выбрать набор инструментов C/C++"},
    {"Request clangd inlay hints, folding, code lens, and include hierarchy",
      "Запросить у clangd inlay hints, folding, code lens и иерархию include"},
    {"Run static checks, sanitizers, coverage, Valgrind, or perf",
      "Запустить статический анализ, sanitizers, coverage, Valgrind или perf"},
    {"Stop the active static-analysis process", "Остановить текущий процесс статического анализа"},
    {"Search and execute an IDE command", "Найти и выполнить команду IDE"},
    {"Configure a user-wide command shortcut", "Настроить пользовательское сочетание клавиш"},
    {"Show effective shortcuts and conflicts", "Показать действующие сочетания и конфликты"},
    {"Select an accessible editor color theme", "Выбрать доступную цветовую тему редактора"},
    {"Override a syntax or diagnostic color role", "Переопределить цвет синтаксиса или диагностики"},
    {"Configure CMake, compilers, environment, and clangd",
      "Настроить CMake, компиляторы, окружение и clangd"},
    {"Activate the previous open file", "Активировать предыдущий открытый файл"},
    {"Activate the next open file", "Активировать следующий открытый файл"},
    {"Clear Output, Problems, Build, Terminal, or Analysis content",
      "Очистить содержимое Output, Problems, Build, Terminal или Analysis"},
    {"Copy all text from the active lower panel", "Скопировать весь текст активной нижней панели"},
    {"Filter diagnostics by file, severity, or message", "Фильтровать диагностику по файлу, уровню или тексту"},
    {"Show the keyboard reference", "Показать справку по клавишам"},
    {"About TUI IDE", "О TUI IDE"},
    {"No matching problems", "Подходящих проблем нет"},
    {"No project", "Нет проекта"}, {"No file", "Нет файла"},
    {"Ln", "Стр"}, {"Col", "Кол"}, {"file(s)", "файлов"},
    {"Configure shortcuts", "Настройка сочетаний"},
    {"&OK", "&ОК"}, {"&Cancel", "О&тмена"},
    {"Find and replace", "Поиск и замена"},
    {"Find:", "Найти:"}, {"Replace:", "Заменить:"},
    {"Case sensitive", "Учитывать регистр"},
    {"Whole word", "Слово целиком"},
    {"Regular expression", "Регулярное выраж."},
    {"Entire project", "Весь проект"},
    {"&Next", "&Далее"}, {"&Previous", "Н&азад"},
    {"&Replace", "&Заменить"}, {"Replace &all", "Заменить &всё"},
    {"&Find all", "&Найти всё"},
    {"Breakpoint properties", "Свойства точки останова"},
    {"Enabled", "Включена"}, {"Condition:", "Условие:"},
    {"Ignore first hits:", "Пропустить раз:"},
    {"Log message:", "Сообщение:"},
    {"A logpoint prints its message and continues automatically.",
      "Лог-точка выводит сообщение и продолжает программу."},
    {"Ignore hit count must be an integer from 0 to 1000000000.",
      "Число пропусков должно быть целым от 0 до 1000000000."},
    {"Open core dump", "Открыть дамп памяти"},
    {"Executable:", "Исполняемый:"}, {"Core dump:", "Дамп памяти:"},
    {"&Browse...", "&Файл..."}, {"B&rowse...", "О&бзор..."},
    {"Bro&wse...", "Об&зор..."},
    {"&Open", "&Открыть"},
    {"Core sessions are read-only: inspect stack, variables, memory and registers.",
      "Дамп только для чтения: стек, переменные, память, регистры."},
    {"Select both an executable and a core dump.",
      "Выберите исполняемый файл и дамп памяти."},
    {"Executable is not a readable regular file: ",
      "Исполняемый файл недоступен для чтения: "},
    {"Core dump is not a readable regular file: ",
      "Дамп памяти недоступен для чтения: "},
    {"Launch configuration", "Конфигурация запуска"},
    {"Run/Debug configurations", "Конфигурации запуска и отладки"},
    {"CMake target:", "Цель CMake:"},
    {"Executable override:", "Исполняемый файл:"},
    {"Working directory:", "Рабочий каталог:"},
    {"Arguments:", "Аргументы:"}, {"Environment:", "Окружение:"},
    {"Stdin file:", "Файл stdin:"},
    {"Build before launch", "Собирать перед запуском"},
    {"External terminal (Run only)", "Внешний терминал (Run)"},
    {"Terminal executable:", "Команда терминала:"},
    {"Example: x-terminal-emulator", "Пример: x-terminal-emulator"},
    {"Use currently selected target", "Использовать текущую цель"},
    {"Select launch working directory", "Выбрать рабочий каталог запуска"},
    {"External terminal command is required.", "Укажите команду внешнего терминала."},
    {"&Add...", "&Добавить..."}, {"&Clone...", "&Копировать..."},
    {"&Edit...", "&Изменить..."}, {"&Delete", "&Удалить"},
    {"&Select", "&Выбрать"}, {"C&ancel", "О&тмена"},
    {"Configuration name:", "Имя конфигурации:"},
    {"Configuration name is required.", "Укажите имя конфигурации."},
    {"A configuration with this name already exists.",
      "Конфигурация с таким именем уже существует."},
    {"current CMake target", "текущая цель CMake"},
    {"Add Run/Debug configuration", "Добавить конфигурацию запуска и отладки"},
    {"Clone Run/Debug configuration", "Копировать конфигурацию запуска и отладки"},
    {"At least one configuration must remain.", "Должна остаться хотя бы одна конфигурация."},
    {"Delete configuration", "Удалить конфигурацию"},
    {"Delete ", "Удалить "},
    {"Configure preset", "Пресет настройки"},
    {"Build preset", "Пресет сборки"},
    {"CMake configure presets", "Пресеты настройки CMake"},
    {"CMake build presets", "Пресеты сборки CMake"},
    {"Name:", "Имя:"}, {"Display name:", "Показываемое имя:"},
    {"Inherits (; separated):", "Наследует (через ;):"},
    {"Generator:", "Генератор:"},
    {"Binary directory:", "Каталог сборки:"},
    {"Configure preset:", "Пресет настройки:"},
    {"Configuration:", "Конфигурация:"},
    {"Targets (; separated):", "Цели (через ;):"},
    {"Clean first", "Сначала очистить"},
    {"Verbose build", "Подробная сборка"},
    {"&Add", "&Добавить"}, {"C&lone", "&Копировать"},
    {"&Edit", "&Изменить"}, {"&Reload", "&Обновить"},
    {"No configure preset", "Без пресета настройки"},
    {"No build preset", "Без пресета сборки"},
    {"editable", "можно изменять"}, {", hidden", ", скрытый"},
    {"CMake presets", "Пресеты CMake"},
    {"Select a preset to clone.", "Выберите пресет для копирования."},
    {"Clone CMake preset", "Копировать пресет CMake"},
    {"Select a preset to edit.", "Выберите пресет для изменения."},
    {"Read-only preset", "Пресет только для чтения"},
    {"Project and included presets are read-only. Clone this preset to edit it.",
      "Пресеты проекта и подключённые пресеты доступны только для чтения. Создайте копию."},
    {"Select a preset to delete.", "Выберите пресет для удаления."},
    {"Only presets from CMakeUserPresets.json can be deleted.",
      "Удалять можно только пресеты из CMakeUserPresets.json."},
    {"Delete CMake preset", "Удалить пресет CMake"},
    {"Delete user preset '", "Удалить пользовательский пресет '"},
    {"Hidden preset", "Скрытый пресет"},
    {"Hidden presets cannot be selected directly.",
      "Скрытый пресет нельзя выбрать напрямую."},
    {"Open CMake project", "Открыть проект CMake"},
    {"Select import build directory", "Выбрать каталог сборки для импорта"},
    {"Select empty project directory", "Выбрать пустой каталог проекта"},
    {"Select build directory", "Выбрать каталог сборки"},
    {"C++ class header path", "Путь заголовка класса C++"},
    {"C++ class implementation path", "Путь реализации класса C++"},
    {"New project file path", "Путь нового файла проекта"},
    {"File name:", "Имя файла:"},
    {"&Up", "&Родитель"},
    {"New &directory", "Новый &каталог"},
    {"&Create", "&Создать"},
    {"Project / ", "Проект / "},
    {"New directory", "Новый каталог"},
    {"Directory name:", "Имя каталога:"},
    {"Enter one valid directory name.", "Укажите одно допустимое имя каталога."},
    {"Cannot create directory: ", "Не удалось создать каталог: "},
    {"Directory already exists.", "Каталог уже существует."},
    {"Enter one valid file name.", "Укажите одно допустимое имя файла."},
    {"The selected file already exists.", "Выбранный файл уже существует."},
    {"C++ class options", "Параметры класса C++"},
    {"Class name:", "Имя класса:"},
    {"Header file:", "Заголовок:"},
    {"Source file:", "Реализация:"},
    {"Namespace:", "Пространство:"},
    {"Base class:", "Базовый класс:"},
    {"Base header:", "Файл базы:"},
    {"Inheritance:", "Наследование:"},
    {"Generate constructor", "Создать конструктор"},
    {"Generate destructor", "Создать деструктор"},
    {"Virtual destructor", "Виртуальный деструктор"},
    {"Final class", "Финальный класс"},
    {"Copy operations", "Операции копирования"},
    {"Move operations", "Операции перемещения"},
    {"&Proceed", "&Далее"},
    {"New project settings", "Параметры нового проекта"},
    {"Project name:", "Имя проекта:"},
    {"Language:", "Язык:"},
    {"Target type:", "Тип цели:"},
    {"Language standard:", "Стандарт:"},
    {"C++ headers:", "Заголовки C++:"},
    {"Generator:", "Генератор:"},
    {"Build type:", "Тип сборки:"},
    {"Install layout:", "Установка:"},
    {"Enable compiler warnings", "Включить предупреждения"},
    {"Create README.md", "Создать README.md"},
    {"Create .gitignore", "Создать .gitignore"},
    {"Enable CTest", "Включить CTest"},
    {"Import source directory", "Импорт каталога исходников"},
    {"Target name:", "Имя цели:"},
    {"&Preview", "&Просмотр"},
    {"Project Settings", "Настройки проекта"},
    {"Source directory:", "Исходный каталог:"},
    {"Build directory:", "Каталог сборки:"},
    {"Toolchain file:", "Файл toolchain:"},
    {"C compiler:", "Компилятор C:"},
    {"C++ compiler:", "C++ компилятор:"},
    {"Debugger:", "Отладчик:"},
    {"DAP adapter:", "Адаптер DAP:"},
    {"C standard:", "Стандарт C:"},
    {"C++ standard:", "Стандарт C++:"},
    {"Jobs:", "Задач:"},
    {"Tab width:", "Табуляция:"},
    {"Insert spaces", "Пробелы вместо Tab"},
    {"Environment:", "Окружение:"},
    {"clangd arguments:", "Аргументы clangd:"},
    {"Use NAME=value; OTHER=value", "Формат: NAME=value; OTHER=value"},
    {"Parallel jobs must be between 1 and 1024.", "Число потоков должно быть от 1 до 1024."},
    {"Tab width must be between 1 and 16.", "Ширина табуляции должна быть от 1 до 16."},
    {"Environment must use NAME=value entries separated by semicolons.",
      "Переменные окружения задаются как NAME=value через точку с запятой."},
    {"Unterminated escape or quote in clangd arguments.",
      "В аргументах clangd не закрыта кавычка или escape-последовательность."},
    {"Build directory is required.", "Укажите каталог сборки."},
    {"Build directory must differ from the source directory.",
      "Каталог сборки должен отличаться от каталога исходников."},
    {"Unsupported C language standard.", "Неподдерживаемый стандарт C."},
    {"Unsupported C++ language standard.", "Неподдерживаемый стандарт C++."},
    {"C++ header extension must be h or hpp.", "Расширение заголовков C++ должно быть h или hpp."},
    {"Unsupported CMake build type.", "Неподдерживаемый тип сборки CMake."},
    {"Debugger backend must be gdb-mi or lldb-dap.",
      "Отладчик должен использовать gdb-mi или lldb-dap."},
    {"Unsupported editor theme.", "Неподдерживаемая тема редактора."},
    {"At least one launch configuration is required.",
      "Нужна хотя бы одна конфигурация запуска."},
    {"Launch configuration name is required.", "Укажите имя конфигурации запуска."},
    {"Active launch configuration was not found.",
      "Активная конфигурация запуска не найдена."},
    {"Command palette", "Палитра команд"},
    {"Keyboard shortcuts", "Горячие клавиши"},
    {"About TUI IDE", "О TUI IDE"},
    {"TUI IDE 0.1\nC/C++ terminal IDE for Linux/amd64\nFinal Cut + clangd + CMake + GDB/MI",
      "TUI IDE 0.1\nТерминальная IDE для C/C++ на Linux/amd64\nFinal Cut + clangd + CMake + GDB/MI"},
    {"Toolchain kits", "Наборы инструментов"},
    {"clangd language insights", "Сведения о языке от clangd"},
    {"Import preview", "Предпросмотр импорта"},
    {"Project replace preview", "Предпросмотр замены в проекте"},
    {"Filter Problems", "Фильтр проблем"},
    {"Text (empty clears):", "Текст (пустой сбрасывает):"},
    {"Project tree filter", "Фильтр дерева проекта"},
    {"Path substring (empty shows all):", "Часть пути:"},
    {"New project directory", "Новый каталог проекта"},
    {"Name or relative path:", "Имя или путь:"},
    {"Rename / Move project entry", "Переименовать / переместить в проекте"},
    {"New project-relative path:", "Новый путь:"},
    {"Select an empty project subdirectory.", "Выберите пустой подкаталог проекта."},
    {"Delete directory", "Удалить каталог"},
    {"Delete empty directory from disk?\n", "Удалить пустой каталог с диска?\n"},
    {"Select a project file or subdirectory to rename.",
      "Выберите файл или подкаталог проекта для переименования."},
    {"Save modified CMake files before Rename / Move.",
      "Сохраните изменённые файлы CMake перед переименованием или перемещением."},
    {"Directory path must be inside the project root.",
      "Путь каталога должен находиться внутри проекта."},
    {"Project path already exists.", "Такой путь в проекте уже существует."},
    {"Select a directory inside the project root.",
      "Выберите каталог внутри проекта."},
    {"Selected path is not a directory.", "Выбранный путь не является каталогом."},
    {"Only empty directories can be deleted safely.",
      "Можно безопасно удалить только пустой каталог."},
    {"Source and destination must be inside the project root.",
      "Исходный и новый пути должны находиться внутри проекта."},
    {"Selected project entry no longer exists.", "Выбранный элемент проекта больше не существует."},
    {"Destination path already exists.", "Новый путь уже существует."},
    {"Destination parent directory does not exist.", "Родительский каталог нового пути не существует."},
    {"Cannot resolve an entry before move.", "Не удалось определить путь элемента перед перемещением."},
    {"Add watch", "Добавить наблюдение"},
    {"Evaluate expression", "Вычислить выражение"},
    {"Set variable value", "Изменить значение переменной"},
    {"Expression:", "Выражение:"},
    {"New value for ", "Новое значение для "},
    {"Disassembly", "Дизассемблирование"},
    {"Address/expression ($pc):", "Адрес/выражение ($pc):"},
    {"Signals", "Сигналы"}, {"Select signal", "Выбрать сигнал"},
    {"Inspect policies (Output)", "Посмотреть политики (Вывод)"},
    {"Configure handling", "Настроить обработку"},
    {"Send signal and continue", "Отправить сигнал и продолжить"},
    {"0 (suppress pending signal)", "0 (подавить ожидающий сигнал)"},
    {"Send ", "Отправить "},
    {" and resume? May terminate program", " и продолжить? Программа может завершиться"},
    {"Send and continue", "Отправить и продолжить"},
    {"Handling of ", "Обработка "},
    {"Stop, print, pass", "Остановить, печатать, передать"},
    {"Stop, print, suppress", "Остановить, печатать, подавить"},
    {"No stop, print, pass", "Не останавливать, печатать, передать"},
    {"No stop, print, suppress", "Не останавливать, печатать, подавить"},
    {"No stop, silent, pass", "Не останавливать, тихо, передать"},
    {"No stop, silent, suppress", "Не останавливать, тихо, подавить"},
    {"Memory view", "Просмотр памяти"},
    {"Address/expression ($sp):", "Адрес/выражение ($sp):"},
    {"Bytes (1..4096):", "Байты (1..4096):"},
    {"Select Run/Debug configuration", "Выбрать конфигурацию запуска/отладки"},
    {"Recent projects", "Недавние проекты"},
    {"New project file", "Новый файл проекта"},
    {"C header (.h)", "Заголовок C (.h)"},
    {"C++ header (.hpp)", "Заголовок C++ (.hpp)"},
    {"C implementation (.c)", "Реализация C (.c)"},
    {"C++ implementation (.cpp)", "Реализация C++ (.cpp)"},
    {"C++ class (.hpp + .cpp)", "Класс C++ (.hpp + .cpp)"},
    {"Remove from CMake project only", "Удалить только из проекта CMake"},
    {"Remove from CMake project and delete from disk",
      "Удалить из проекта CMake и с диска"},
    {"Open or create a project first.", "Сначала откройте или создайте проект."},
    {"Save modified CMake files before adding a project file.",
      "Сохраните изменённые файлы CMake перед добавлением файла в проект."},
    {"Select a file to remove. Directories are not removed.",
      "Выберите файл для удаления. Каталоги не удаляются."},
    {"The selected file is outside the project root.",
      "Выбранный файл находится вне каталога проекта."},
    {"Save or close the modified file before deleting it.",
      "Сохраните или закройте изменённый файл перед удалением."},
    {"Delete file", "Удалить файл"},
    {"Permanently delete from disk?\n", "Безвозвратно удалить с диска?\n"},
    {"Remove all breakpoints", "Удалить все точки останова"},
    {"Remove every breakpoint in this project?", "Удалить все точки останова в этом проекте?"},
    {"CMake completion", "Автодополнение CMake"},
    {"Workspace symbols", "Символы проекта"},
    {"Name or substring:", "Имя или его часть:"},
    {"Go to line", "Перейти к строке"},
    {"Line number:", "Номер строки:"},
    {"File deleted outside TUI IDE", "Файл удалён вне TUI IDE"},
    {"File changed outside TUI IDE", "Файл изменён вне TUI IDE"},
    {"Crash recovery", "Восстановление после сбоя"},
    {"CMake executable target", "Исполняемая цель CMake"},
    {"CTest preset", "Пресет CTest"},
    {"Analysis and profiling tool", "Инструмент анализа и профилирования"},
    {"Analysis scope", "Область анализа"},
    {"Attach to Process", "Подключиться к процессу"},
    {"Rename symbol", "Переименовать символ"},
    {"New name:", "Новое имя:"},
    {"clangd completion", "Автодополнение clangd"},
    {"Signature help", "Подсказка сигнатуры"},
    {"Symbol information", "Сведения о символе"},
    {"References", "Ссылки"},
    {"Organize Includes", "Упорядочить include"},
    {"Code Actions", "Действия с кодом"},
    {"Workspace Symbols", "Символы проекта"},
    {"File: New", "Файл: Создать"}, {"File: Open", "Файл: Открыть"},
    {"File: Save", "Файл: Сохранить"}, {"File: Close", "Файл: Закрыть"},
    {"File: Close All", "Файл: Закрыть все"},
    {"File: Reopen Closed", "Файл: Открыть закрытый"},
    {"Search: Find and Replace", "Поиск: Найти и заменить"},
    {"Search: Go to Line", "Поиск: Перейти к строке"},
    {"Search: Go to Definition", "Поиск: К определению"},
    {"Search: Find References", "Поиск: Найти ссылки"},
    {"Search: Problems", "Поиск: Проблемы"},
    {"Search: Next Diagnostic", "Поиск: Следующая диагностика"},
    {"Debug: Start / Continue", "Отладка: Старт / продолжить"},
    {"Run: Run", "Запуск: Выполнить"}, {"Run: Build", "Запуск: Собрать"},
    {"Run: Select Configuration", "Запуск: Выбрать конфигурацию"},
    {"Run: Launch Configuration", "Запуск: Настроить конфигурацию"},
    {"Debug: Toggle Breakpoint", "Отладка: Переключить точку останова"},
    {"Debug: Step Into", "Отладка: Шаг внутрь"},
    {"Debug: Step Over / Next", "Отладка: Следующий шаг"},
    {"Debug: Step Out", "Отладка: Шаг наружу"},
    {"Debug: Add Watch", "Отладка: Добавить наблюдение"},
    {"Tools: Completion", "Сервис: Автодополнение"},
    {"Tools: Symbol Information", "Сервис: Сведения о символе"},
    {"Tools: Rename Symbol", "Сервис: Переименовать символ"},
    {"Tools: Code Actions", "Сервис: Действия с кодом"},
    {"Window: Previous File", "Окно: Предыдущий файл"},
    {"Window: Next File", "Окно: Следующий файл"},
    {"Window: Previous Sidebar Tab", "Окно: Предыдущая боковая вкладка"},
    {"Window: Next Sidebar Tab", "Окно: Следующая боковая вкладка"},
    {"Window: Previous Lower Tab", "Окно: Предыдущая нижняя вкладка"},
    {"Window: Next Lower Tab", "Окно: Следующая нижняя вкладка"},
    {"Editor theme", "Тема редактора"}, {"Editor colors", "Цвета редактора"},
    {"Search:", "Поиск:"}, {"Default:", "По умолчанию:"},
    {"Current:", "Текущее:"}, {"Default: ", "По умолчанию: "},
    {"Current: ", "Текущее: "}, {"None", "Нет"},
    {"&Capture", "&Записать"}, {"C&lear", "О&чистить"},
    {"Reset &selected", "Сбросить &выбранное"}, {"Reset &all", "Сбросить &всё"},
    {"A&pply", "&Применить"}, {"&Apply", "&Применить"},
    {"Ca&ncel", "От&мена"}, {"&Reset", "&Сбросить"},
    {"Create &copy", "Создать &копию"}, {"Reset &role", "Сбросить &роль"},
    {"Palette:", "Палитра:"}, {"Theme default", "По умолчанию темы"},
    {"Type a supported shortcut, or use Clear to disable this command.",
      "Введите сочетание или нажмите «Очистить», чтобы отключить команду."},
    {"Press the desired key now (Escape cancels capture).",
      "Нажмите нужную клавишу (Escape отменяет захват)."},
    {"Capture cancelled.", "Захват отменён."},
    {"Unsupported key. Use Ctrl/Alt combinations, Ctrl+F8, or F1-F12.",
      "Клавиша не поддерживается. Используйте Ctrl/Alt, Ctrl+F8 или F1–F12."},
    {"Ready. Changes are saved only after Apply.",
      "Готово. Изменения сохранятся после нажатия «Применить»."},
    {"Dark", "Тёмная"}, {"Light", "Светлая"},
    {"High contrast", "Контрастная"},
    {"built-in", "встроенная"}, {"copy of ", "копия "},
    {"User theme — editable color overrides", "Тема пользователя — цвета можно изменить"},
    {"Built-in theme — read-only", "Встроенная тема — только чтение"},
    {"Preview: ", "Предпросмотр: "}, {"Base palette: ", "Базовая палитра: "},
    {"Create theme copy", "Создать копию темы"}, {"Theme name:", "Имя темы:"},
    {"Theme name is empty, reserved, or already exists.",
      "Имя темы пустое, зарезервировано или уже существует."},
    {"Terminal palette: ", "Палитра терминала: "},
    {" colors | Theme: ", " цветов | Тема: "},
    {" | Effective: ", " | Итог: "}, {" | Override: ", " | Замена: "},
    {"foreground", "основной текст"}, {"background", "фон"},
    {"gutter", "поле строк"}, {"breakpoint", "точка останова"},
    {"diagnosticError", "ошибка"}, {"diagnosticWarning", "предупреждение"},
    {"diagnosticNote", "примечание"}, {"selectionForeground", "текст выделения"},
    {"selectionBackground", "фон выделения"},
    {"executionLineBackground", "фон строки отладки"},
    {"plain", "обычный текст"}, {"keyword", "ключевое слово"},
    {"type", "тип"}, {"string", "строка"}, {"number", "число"},
    {"comment", "комментарий"}, {"preprocessor", "препроцессор"},
    {"namespace", "пространство имён"}, {"function", "функция"},
    {"variable", "переменная"}, {"parameter", "параметр"},
    {"property", "свойство"}, {"macro", "макрос"},
    {"enumMember", "элемент перечисления"},
    {"Black", "Чёрный"}, {"Blue", "Синий"}, {"Green", "Зелёный"},
    {"Cyan", "Бирюзовый"}, {"Red", "Красный"}, {"Magenta", "Пурпурный"},
    {"Brown", "Коричневый"}, {"LightGray", "Светло-серый"},
    {"DarkGray", "Тёмно-серый"}, {"LightBlue", "Светло-синий"},
    {"LightGreen", "Светло-зелёный"}, {"LightCyan", "Светло-бирюзовый"},
    {"LightRed", "Светло-красный"}, {"LightMagenta", "Светло-пурпурный"},
    {"Yellow", "Жёлтый"}, {"White", "Белый"},
  };
  const auto translation = russian.find(english);
  return std::string(translation == russian.end() ? english : translation->second);
}

auto keyboardHelpText(std::string_view language) -> std::string_view {
  constexpr std::string_view english =
    "F10 or Alt+F/E/S/R/P/D/T/W/H  Menu; underlines local, shortcuts global\n"
    "Ctrl+N/O/S/W  Files\n"
    "F1/F2/F3/F4  Info/Rename/Definition/References\n"
    "F5/F6        Debug/Run   Ctrl+B Build\n"
    "F7/F8        Step into/over   Alt+F8 Step out\n"
    "F9           Breakpoint   Ctrl+F8 Next diagnostic\n"
    "Alt+PgUp/Dn  Previous/next sidebar tab\n"
    "Alt+Shift+PgUp/Dn  Previous/next lower tab\n"
    "Ctrl+F       Find/Replace text or project\n"
    "Ctrl+P, Alt+B, Ctrl+T  Configure/Build preset/Target\n"
    "Alt+L / Alt+Shift+L  Manage / select Run/Debug configuration\n"
    "Alt+Shift+U  Add a GDB watch expression\n"
    "Ctrl+L       Redraw screen (reserved by Final Cut)\n"
    "Alt+K        Search the command palette\n"
    "Alt+A        clangd Code Actions / Quick Fixes\n"
    "Ctrl+E       Focus Project explorer\n"
    "Insert       Add file/class template in Project\n"
    "Delete       Remove selected Project file\n"
    "Window menu  Open files/Project/Debug panel";
  constexpr std::string_view russian =
    "F10 или Alt+F/E/S/R/P/D/T/W/H  Меню\n"
    "Ctrl+N/O/S/W  Файлы\n"
    "F1/F2/F3/F4  Сведения/Имя/Определение/Ссылки\n"
    "F5/F6        Отладка/Запуск   Ctrl+B Сборка\n"
    "F7/F8        Шаг внутрь/через   Alt+F8 Шаг наружу\n"
    "F9           Точка останова   Ctrl+F8 Диагностика\n"
    "Alt+PgUp/Dn  Вкладки боковой панели\n"
    "Alt+Shift+PgUp/Dn  Вкладки нижней панели\n"
    "Ctrl+F       Поиск/замена в файле или проекте\n"
    "Ctrl+P, Alt+B, Ctrl+T  Пресеты/Цель CMake\n"
    "Alt+L / Alt+Shift+L  Управление/выбор запуска\n"
    "Alt+Shift+U  Добавить выражение наблюдения\n"
    "Ctrl+L       Перерисовать экран (Final Cut)\n"
    "Alt+K        Палитра команд\n"
    "Alt+A        Действия с кодом clangd\n"
    "Ctrl+E       Фокус на дереве проекта\n"
    "Insert       Добавить файл или класс в проект\n"
    "Delete       Удалить выбранный файл проекта\n"
    "Меню Окно    Панели файлов, проекта и отладки";
  return language == "ru" ? russian : english;
}

}  // namespace tuiide
