#include "tuiide/ui_localization.hpp"

#include <unordered_map>

namespace tuiide {

auto localizedUiText(std::string_view language, std::string_view english) -> std::string {
  if (language != "ru") return std::string(english);
  // Ключи совпадают с исходными подписями Final Cut; & обозначает mnemonic.
  static const std::unordered_map<std::string_view, std::string_view> russian{
    {"&File", "&Файл"}, {"&Edit", "&Правка"}, {"&Search", "П&оиск"},
    {"&Run", "&Запуск"}, {"&Project", "Про&ект"}, {"&Debug", "&Отладка"},
    {"&Tools", "&Сервис"}, {"&Window", "О&кно"}, {"&Help", "С&правка"},
    {"&Tests", "&Тесты"},
    {"New &Project...", "Новый &проект..."},
    {"&Open Project...", "&Открыть проект..."},
    {"Recent P&rojects...", "Недавние про&екты..."},
    {"Close Pro&ject", "&Закрыть проект"},
    {"&New", "&Новый файл"}, {"New from &template...", "Из &шаблона..."},
    {"Open f&ile...", "Открыть &файл..."}, {"Recent &Files", "Недавние &файлы"},
    {"&Save", "&Сохранить"}, {"Save A&ll", "Сохранить &все"},
    {"Save &As...", "Сохранить &как..."}, {"&Close", "&Закрыть"},
    {"Close Ot&hers", "Закрыть &остальные"}, {"Clos&e All", "Закрыть в&се"},
    {"Reopen Close&d", "Открыть закры&тый"}, {"E&xit", "В&ыход"},
    {"&Undo", "&Отменить"}, {"&Redo", "&Повторить"}, {"Cu&t", "Выреза&ть"},
    {"&Copy", "&Копировать"}, {"&Paste", "&Вставить"},
    {"Select &All", "Выделить &всё"}, {"Toggle co&mment", "Переключить ко&мментарий"},
    {"Duplicate l&ine", "Дублировать &строку"}, {"Move li&ne up", "Строку в&верх"},
    {"Move line do&wn", "Строку вни&з"}, {"De&lete line", "&Удалить строку"},
    {"&Find...", "&Найти..."}, {"Find &next", "Следу&ющее совпадение"},
    {"Find &previous", "Пре&дыдущее совпадение"}, {"&Replace...", "&Заменить..."},
    {"Find in pro&ject...", "Найти в про&екте..."}, {"&Go to line...", "&Перейти к строке..."},
    {"Go to &definition", "К &определению"}, {"Find r&eferences", "Найти &ссылки"},
    {"Pro&blems...", "Пр&облемы..."}, {"Next d&iagnostic", "Следующая &диагностика"},
    {"C&onfigure", "&Настроить"}, {"&Build", "&Собрать"},
    {"&Rebuild", "Пере&собрать"}, {"C&lean", "О&чистить"},
    {"Cancel B&uild", "Отменить сбо&рку"}, {"Ru&n", "За&пустить"},
    {"Stop progra&m", "Остановить програ&мму"},
    {"Select &active configuration...", "Выбрать &конфигурацию..."},
    {"Manage &Debug/Run configurations...", "Настроить запуск и &отладку..."},
    {"Configure &preset...", "Пресет &конфигурации..."},
    {"Build pre&set...", "Пресет сбо&рки..."}, {"Select tar&get...", "Выбрать &цель..."},
    {"&Discover tests", "&Найти тесты"}, {"Run &all tests", "Запустить &все тесты"},
    {"Run &selected test", "Запустить &выбранный тест"},
    {"Rerun &failed tests", "Повторить &упавшие тесты"},
    {"Test &preset...", "&Пресет тестов..."}, {"S&top tests", "Ос&тановить тесты"},
    {"&Refresh tree", "&Обновить дерево"}, {"&Filter...", "&Фильтр..."},
    {"&Clear filter", "С&бросить фильтр"}, {"New &directory...", "Новый &каталог..."},
    {"Rename / &Move...", "Переименовать / &переместить..."},
    {"Delete director&y", "Удалить катало&г"},
    {"&Start / Continue", "&Старт / продолжить"}, {"Pa&use", "Пау&за"},
    {"S&top", "Ос&тановить"}, {"&Restart", "&Перезапустить"},
    {"Attach to process...", "Подключиться к процессу..."},
    {"Open &core dump...", "Открыть &дамп памяти..."},
    {"Toggle &breakpoint", "Переключить &точку останова"},
    {"Breakpoint &properties...", "&Свойства точки останова..."},
    {"Enable / &disable breakpoint", "Включить / &выключить точку"},
    {"Remove brea&kpoint", "Удалить то&чку"},
    {"Remove &all breakpoints", "Удалить &все точки"},
    {"&Next", "&Следующий шаг"}, {"Step &into", "Шаг &внутрь"},
    {"Step &out", "Шаг &наружу"}, {"Add &watch...", "Добавить &наблюдение..."},
    {"&Evaluate expression...", "&Вычислить выражение..."},
    {"Set &variable value...", "Изменить &переменную..."},
    {"Disassembl&y...", "&Дизассемблирование..."}, {"&Memory...", "&Память..."},
    {"Toggle re&gisters", "Переключить &регистры"},
    {"Signal &handling...", "Обработка &сигналов..."},
    {"Co&mpletion", "Автодо&полнение"}, {"Signature &help...", "Подсказка &сигнатуры..."},
    {"Symbol &information", "Сведения о &символе"},
    {"&Rename symbol...", "&Переименовать символ..."},
    {"Code &actions...", "&Действия с кодом..."},
    {"Organize incl&udes", "Упорядочить &include"},
    {"Switch header / &source", "Переключить заголовок / &исходник"},
    {"&Workspace symbols...", "&Символы проекта..."},
    {"Ca&ll hierarchy...", "Иерархия &вызовов..."},
    {"Type hierarch&y...", "Иерархия &типов..."},
    {"Format &document", "Форматировать &документ"},
    {"Format selectio&n", "Форматировать в&ыделение"},
    {"Toolchain &kits...", "Наборы &инструментов..."},
    {"Language insights...", "Сведения о языке..."},
    {"Run analysis / profil&e...", "Запустить анализ / профилирование..."},
    {"Stop analysis acti&vity", "Остановить &анализ"},
    {"Command &palette...", "Палитра &команд..."},
    {"Configure sh&ortcut...", "Настроить &сочетание..."},
    {"Shortcut con&flicts...", "Конфликты &сочетаний..."},
    {"Editor &theme...", "&Тема редактора..."},
    {"Editor &colors...", "&Цвета редактора..."},
    {"Project settin&gs...", "Настройки &проекта..."},
    {"Interface language", "Язык интерфейса"},
    {"&Previous file", "&Предыдущий файл"}, {"&Next file", "&Следующий файл"},
    {"Show Open &files", "Показать открытые &файлы"},
    {"Show pr&oject", "Показать про&ект"}, {"Show O&utline", "Показать структуру"},
    {"Show &Debug", "Показать &отладку"},
    {"Show &Breakpoints", "Показать точки &останова"},
    {"Show T&ests", "Показать &тесты"}, {"Show &Git", "Показать &Git"},
    {"&Clear active lower panel", "&Очистить нижнюю панель"},
    {"Cop&y active lower panel", "&Копировать нижнюю панель"},
    {"Filter proble&ms...", "Фильтр пробле&м..."},
    {"Sidebar n&arrower", "Сделать боковую панель у&же"},
    {"Sidebar &wider", "Сделать боковую панель &шире"},
    {"Lower panel &shorter", "У&меньшить нижнюю панель"},
    {"Lower panel &taller", "У&величить нижнюю панель"},
    {"&Reset panel sizes", "&Сбросить размеры панелей"},
    {"&Keyboard shortcuts", "&Горячие клавиши"},
    {"&About TUI IDE", "&О TUI IDE"},
    {"Open files", "Открытые файлы"}, {"Project", "Проект"},
    {"Outline", "Структура"}, {"Debug", "Отладка"},
    {"Breakpoints", "Точки останова"}, {"Tests", "Тесты"},
    {"Output", "Вывод"}, {"Problems", "Проблемы"},
    {"Build", "Сборка"}, {"Terminal", "Терминал"},
    {"Analysis", "Анализ"}, {"Build output", "Вывод сборки"},
    {"Analysis output", "Вывод анализа"}, {"No problems", "Проблем нет"},
    {"No matching problems", "Подходящих проблем нет"},
    {"No project", "Нет проекта"}, {"No file", "Нет файла"},
    {"Ln", "Стр"}, {"Col", "Кол"}, {"file(s)", "файлов"},
    {"Configure shortcuts", "Настройка сочетаний"},
    {"&OK", "&ОК"}, {"&Cancel", "О&тмена"},
    {"Command palette", "Палитра команд"},
    {"Keyboard shortcuts", "Горячие клавиши"},
    {"Toolchain kits", "Наборы инструментов"},
    {"clangd language insights", "Сведения о языке от clangd"},
    {"Import preview", "Предпросмотр импорта"},
    {"Project replace preview", "Предпросмотр замены в проекте"},
    {"Filter Problems", "Фильтр проблем"},
    {"Text (empty clears):", "Текст (пустой сбрасывает):"},
    {"Project tree filter", "Фильтр дерева проекта"},
    {"Path substring (empty shows all):", "Часть пути (пустой показывает всё):"},
    {"New project directory", "Новый каталог проекта"},
    {"Name or relative path:", "Имя или относительный путь:"},
    {"Rename / Move project entry", "Переименовать / переместить в проекте"},
    {"New project-relative path:", "Новый путь относительно проекта:"},
    {"Add watch", "Добавить наблюдение"},
    {"Evaluate expression", "Вычислить выражение"},
    {"Set variable value", "Изменить значение переменной"},
    {"Expression:", "Выражение:"},
    {"Disassembly", "Дизассемблирование"},
    {"Address/expression ($pc):", "Адрес/выражение ($pc):"},
    {"Signals", "Сигналы"}, {"Select signal", "Выбрать сигнал"},
    {"Memory view", "Просмотр памяти"},
    {"Address/expression ($sp):", "Адрес/выражение ($sp):"},
    {"Bytes (1..4096):", "Байты (1..4096):"},
    {"Select Run/Debug configuration", "Выбрать конфигурацию запуска/отладки"},
    {"Recent projects", "Недавние проекты"},
    {"New project file", "Новый файл проекта"},
    {"CMake completion", "Автодополнение CMake"},
    {"Workspace symbols", "Символы проекта"},
    {"Name or substring:", "Имя или его часть:"},
    {"Go to line", "Перейти к строке"},
    {"Line number:", "Номер строки:"},
    {"File deleted outside TUI IDE", "Файл удалён вне TUI IDE"},
    {"File changed outside TUI IDE", "Файл изменён вне TUI IDE"},
    {"Crash recovery", "Восстановление после сбоя"},
    {"CMake executable target", "Исполняемая цель CMake"},
    {"CTest preset", "Пресет CTest"},
    {"Analysis and profiling tool", "Инструмент анализа и профилирования"},
    {"Analysis scope", "Область анализа"},
    {"Attach to Process", "Подключиться к процессу"},
    {"Rename symbol", "Переименовать символ"},
    {"New name:", "Новое имя:"},
    {"clangd completion", "Автодополнение clangd"},
    {"Signature help", "Подсказка сигнатуры"},
    {"Symbol information", "Сведения о символе"},
    {"References", "Ссылки"},
    {"Organize Includes", "Упорядочить include"},
    {"Code Actions", "Действия с кодом"},
    {"Workspace Symbols", "Символы проекта"},
    {"File: New", "Файл: Создать"}, {"File: Open", "Файл: Открыть"},
    {"File: Save", "Файл: Сохранить"}, {"File: Close", "Файл: Закрыть"},
    {"File: Close All", "Файл: Закрыть все"},
    {"File: Reopen Closed", "Файл: Открыть закрытый"},
    {"Search: Find and Replace", "Поиск: Найти и заменить"},
    {"Search: Go to Line", "Поиск: Перейти к строке"},
    {"Search: Go to Definition", "Поиск: К определению"},
    {"Search: Find References", "Поиск: Найти ссылки"},
    {"Search: Problems", "Поиск: Проблемы"},
    {"Search: Next Diagnostic", "Поиск: Следующая диагностика"},
    {"Debug: Start / Continue", "Отладка: Старт / продолжить"},
    {"Run: Run", "Запуск: Выполнить"}, {"Run: Build", "Запуск: Собрать"},
    {"Run: Select Configuration", "Запуск: Выбрать конфигурацию"},
    {"Run: Launch Configuration", "Запуск: Настроить конфигурацию"},
    {"Debug: Toggle Breakpoint", "Отладка: Переключить точку останова"},
    {"Debug: Step Into", "Отладка: Шаг внутрь"},
    {"Debug: Step Over / Next", "Отладка: Следующий шаг"},
    {"Debug: Step Out", "Отладка: Шаг наружу"},
    {"Debug: Add Watch", "Отладка: Добавить наблюдение"},
    {"Tools: Completion", "Сервис: Автодополнение"},
    {"Tools: Symbol Information", "Сервис: Сведения о символе"},
    {"Tools: Rename Symbol", "Сервис: Переименовать символ"},
    {"Tools: Code Actions", "Сервис: Действия с кодом"},
    {"Window: Previous File", "Окно: Предыдущий файл"},
    {"Window: Next File", "Окно: Следующий файл"},
    {"Window: Previous Sidebar Tab", "Окно: Предыдущая боковая вкладка"},
    {"Window: Next Sidebar Tab", "Окно: Следующая боковая вкладка"},
    {"Window: Previous Lower Tab", "Окно: Предыдущая нижняя вкладка"},
    {"Window: Next Lower Tab", "Окно: Следующая нижняя вкладка"},
    {"Editor theme", "Тема редактора"}, {"Editor colors", "Цвета редактора"},
    {"Search:", "Поиск:"}, {"Default:", "По умолчанию:"},
    {"Current:", "Текущее:"}, {"Default: ", "По умолчанию: "},
    {"Current: ", "Текущее: "}, {"None", "Нет"},
    {"&Capture", "&Записать"}, {"C&lear", "О&чистить"},
    {"Reset &selected", "Сбросить &выбранное"}, {"Reset &all", "Сбросить &всё"},
    {"A&pply", "&Применить"}, {"&Apply", "&Применить"},
    {"Ca&ncel", "От&мена"}, {"&Reset", "&Сбросить"},
    {"Create &copy", "Создать &копию"}, {"Reset &role", "Сбросить &роль"},
    {"Palette:", "Палитра:"}, {"Theme default", "По умолчанию темы"},
    {"Type a supported shortcut, or use Clear to disable this command.",
      "Введите сочетание или нажмите «Очистить», чтобы отключить команду."},
    {"Press the desired key now (Escape cancels capture).",
      "Нажмите нужную клавишу (Escape отменяет захват)."},
    {"Capture cancelled.", "Захват отменён."},
    {"Unsupported key. Use Ctrl/Alt combinations, Ctrl+F8, or F1-F12.",
      "Клавиша не поддерживается. Используйте Ctrl/Alt, Ctrl+F8 или F1–F12."},
    {"Ready. Changes are saved only after Apply.",
      "Готово. Изменения сохранятся после нажатия «Применить»."},
    {"Dark", "Тёмная"}, {"Light", "Светлая"},
    {"High contrast", "Контрастная"},
    {"built-in", "встроенная"}, {"copy of ", "копия "},
    {"User theme — editable color overrides", "Тема пользователя — цвета можно изменить"},
    {"Built-in theme — read-only", "Встроенная тема — только чтение"},
    {"Preview: ", "Предпросмотр: "}, {"Base palette: ", "Базовая палитра: "},
    {"Create theme copy", "Создать копию темы"}, {"Theme name:", "Имя темы:"},
    {"Theme name is empty, reserved, or already exists.",
      "Имя темы пустое, зарезервировано или уже существует."},
    {"Terminal palette: ", "Палитра терминала: "},
    {" colors | Theme: ", " цветов | Тема: "},
    {" | Effective: ", " | Итог: "}, {" | Override: ", " | Замена: "},
    {"foreground", "основной текст"}, {"background", "фон"},
    {"gutter", "поле строк"}, {"breakpoint", "точка останова"},
    {"diagnosticError", "ошибка"}, {"diagnosticWarning", "предупреждение"},
    {"diagnosticNote", "примечание"}, {"selectionForeground", "текст выделения"},
    {"selectionBackground", "фон выделения"},
    {"executionLineBackground", "фон строки отладки"},
    {"plain", "обычный текст"}, {"keyword", "ключевое слово"},
    {"type", "тип"}, {"string", "строка"}, {"number", "число"},
    {"comment", "комментарий"}, {"preprocessor", "препроцессор"},
    {"namespace", "пространство имён"}, {"function", "функция"},
    {"variable", "переменная"}, {"parameter", "параметр"},
    {"property", "свойство"}, {"macro", "макрос"},
    {"enumMember", "элемент перечисления"},
    {"Black", "Чёрный"}, {"Blue", "Синий"}, {"Green", "Зелёный"},
    {"Cyan", "Бирюзовый"}, {"Red", "Красный"}, {"Magenta", "Пурпурный"},
    {"Brown", "Коричневый"}, {"LightGray", "Светло-серый"},
    {"DarkGray", "Тёмно-серый"}, {"LightBlue", "Светло-синий"},
    {"LightGreen", "Светло-зелёный"}, {"LightCyan", "Светло-бирюзовый"},
    {"LightRed", "Светло-красный"}, {"LightMagenta", "Светло-пурпурный"},
    {"Yellow", "Жёлтый"}, {"White", "Белый"},
  };
  const auto translation = russian.find(english);
  return std::string(translation == russian.end() ? english : translation->second);
}

}  // namespace tuiide
