#include "tuiide/ui_localization.hpp"

#include <unordered_map>

namespace tuiide {

auto localizedUiText(std::string_view language, std::string_view english) -> std::string {
  if (language != "ru") return std::string(english);
  // Ключи совпадают с исходными подписями Final Cut; & обозначает mnemonic.
  static const std::unordered_map<std::string_view, std::string_view> russian{
    {"&File", "&Файл"}, {"&Edit", "&Правка"}, {"&Search", "П&оиск"},
    {"&Run", "&Запуск"}, {"&Project", "Про&ект"}, {"&Debug", "&Отладка"},
    {"&Tools", "&Сервис"}, {"&Window", "О&кно"}, {"&Help", "С&правка"},
    {"&Tests", "&Тесты"},
    {"New &Project...", "Новый &проект..."},
    {"&Open Project...", "&Открыть проект..."},
    {"Recent P&rojects...", "Недавние про&екты..."},
    {"Close Pro&ject", "&Закрыть проект"},
    {"&New", "&Новый файл"}, {"New from &template...", "Из &шаблона..."},
    {"Open f&ile...", "Открыть &файл..."}, {"Recent &Files", "Недавние &файлы"},
    {"&Save", "&Сохранить"}, {"Save A&ll", "Сохранить &все"},
    {"Save &As...", "Сохранить &как..."}, {"&Close", "&Закрыть"},
    {"Close Ot&hers", "Закрыть &остальные"}, {"Clos&e All", "Закрыть в&се"},
    {"Reopen Close&d", "Открыть закры&тый"}, {"E&xit", "В&ыход"},
    {"&Undo", "&Отменить"}, {"&Redo", "&Повторить"}, {"Cu&t", "Выреза&ть"},
    {"&Copy", "&Копировать"}, {"&Paste", "&Вставить"},
    {"Select &All", "Выделить &всё"}, {"Toggle co&mment", "Переключить ко&мментарий"},
    {"Duplicate l&ine", "Дублировать &строку"}, {"Move li&ne up", "Строку в&верх"},
    {"Move line do&wn", "Строку вни&з"}, {"De&lete line", "&Удалить строку"},
    {"&Find...", "&Найти..."}, {"Find &next", "Следу&ющее совпадение"},
    {"Find &previous", "Пре&дыдущее совпадение"}, {"&Replace...", "&Заменить..."},
    {"Find in pro&ject...", "Найти в про&екте..."}, {"&Go to line...", "&Перейти к строке..."},
    {"Go to &definition", "К &определению"}, {"Find r&eferences", "Найти &ссылки"},
    {"Pro&blems...", "Пр&облемы..."}, {"Next d&iagnostic", "Следующая &диагностика"},
    {"C&onfigure", "&Настроить"}, {"&Build", "&Собрать"},
    {"&Rebuild", "Пере&собрать"}, {"C&lean", "О&чистить"},
    {"Cancel B&uild", "Отменить сбо&рку"}, {"Ru&n", "За&пустить"},
    {"Stop progra&m", "Остановить програ&мму"},
    {"Select &active configuration...", "Выбрать &конфигурацию..."},
    {"Manage &Debug/Run configurations...", "Настроить запуск и &отладку..."},
    {"Configure &preset...", "Пресет &конфигурации..."},
    {"Build pre&set...", "Пресет сбо&рки..."}, {"Select tar&get...", "Выбрать &цель..."},
    {"&Discover tests", "&Найти тесты"}, {"Run &all tests", "Запустить &все тесты"},
    {"Run &selected test", "Запустить &выбранный тест"},
    {"Rerun &failed tests", "Повторить &упавшие тесты"},
    {"Test &preset...", "&Пресет тестов..."}, {"S&top tests", "Ос&тановить тесты"},
    {"&Refresh tree", "&Обновить дерево"}, {"&Filter...", "&Фильтр..."},
    {"&Clear filter", "С&бросить фильтр"}, {"New &directory...", "Новый &каталог..."},
    {"Rename / &Move...", "Переименовать / &переместить..."},
    {"Delete director&y", "Удалить катало&г"},
    {"&Start / Continue", "&Старт / продолжить"}, {"Pa&use", "Пау&за"},
    {"S&top", "Ос&тановить"}, {"&Restart", "&Перезапустить"},
    {"Attach to process...", "Подключиться к процессу..."},
    {"Open &core dump...", "Открыть &дамп памяти..."},
    {"Toggle &breakpoint", "Переключить &точку останова"},
    {"Breakpoint &properties...", "&Свойства точки останова..."},
    {"Enable / &disable breakpoint", "Включить / &выключить точку"},
    {"Remove brea&kpoint", "Удалить то&чку"},
    {"Remove &all breakpoints", "Удалить &все точки"},
    {"&Next", "&Следующий шаг"}, {"Step &into", "Шаг &внутрь"},
    {"Step &out", "Шаг &наружу"}, {"Add &watch...", "Добавить &наблюдение..."},
    {"&Evaluate expression...", "&Вычислить выражение..."},
    {"Set &variable value...", "Изменить &переменную..."},
    {"Disassembl&y...", "&Дизассемблирование..."}, {"&Memory...", "&Память..."},
    {"Toggle re&gisters", "Переключить &регистры"},
    {"Signal &handling...", "Обработка &сигналов..."},
    {"Co&mpletion", "Автодо&полнение"}, {"Signature &help...", "Подсказка &сигнатуры..."},
    {"Symbol &information", "Сведения о &символе"},
    {"&Rename symbol...", "&Переименовать символ..."},
    {"Code &actions...", "&Действия с кодом..."},
    {"Organize incl&udes", "Упорядочить &include"},
    {"Switch header / &source", "Переключить заголовок / &исходник"},
    {"&Workspace symbols...", "&Символы проекта..."},
    {"Ca&ll hierarchy...", "Иерархия &вызовов..."},
    {"Type hierarch&y...", "Иерархия &типов..."},
    {"Format &document", "Форматировать &документ"},
    {"Format selectio&n", "Форматировать в&ыделение"},
    {"Toolchain &kits...", "Наборы &инструментов..."},
    {"Language insights...", "Сведения о языке..."},
    {"Run analysis / profil&e...", "Запустить анализ / профилирование..."},
    {"Stop analysis acti&vity", "Остановить &анализ"},
    {"Command &palette...", "Палитра &команд..."},
    {"Configure sh&ortcut...", "Настроить &сочетание..."},
    {"Shortcut con&flicts...", "Конфликты &сочетаний..."},
    {"Editor &theme...", "&Тема редактора..."},
    {"Editor &colors...", "&Цвета редактора..."},
    {"Project settin&gs...", "Настройки &проекта..."},
    {"Interface language", "Язык интерфейса"},
    {"&Previous file", "&Предыдущий файл"}, {"&Next file", "&Следующий файл"},
    {"Show Open &files", "Показать открытые &файлы"},
    {"Show pr&oject", "Показать про&ект"}, {"Show O&utline", "Показать структуру"},
    {"Show &Debug", "Показать &отладку"},
    {"Show &Breakpoints", "Показать точки &останова"},
    {"Show T&ests", "Показать &тесты"}, {"Show &Git", "Показать &Git"},
    {"&Clear active lower panel", "&Очистить нижнюю панель"},
    {"Cop&y active lower panel", "&Копировать нижнюю панель"},
    {"Filter proble&ms...", "Фильтр пробле&м..."},
    {"Sidebar n&arrower", "Сделать боковую панель у&же"},
    {"Sidebar &wider", "Сделать боковую панель &шире"},
    {"Lower panel &shorter", "У&меньшить нижнюю панель"},
    {"Lower panel &taller", "У&величить нижнюю панель"},
    {"&Reset panel sizes", "&Сбросить размеры панелей"},
    {"&Keyboard shortcuts", "&Горячие клавиши"},
    {"&About TUI IDE", "&О TUI IDE"},
    {"Open files", "Открытые файлы"}, {"Project", "Проект"},
    {"Outline", "Структура"}, {"Debug", "Отладка"},
    {"Breakpoints", "Точки останова"}, {"Tests", "Тесты"},
    {"Output", "Вывод"}, {"Problems", "Проблемы"},
    {"Build", "Сборка"}, {"Terminal", "Терминал"},
    {"Analysis", "Анализ"}, {"Build output", "Вывод сборки"},
    {"Analysis output", "Вывод анализа"}, {"No problems", "Проблем нет"},
    {"No matching problems", "Подходящих проблем нет"},
    {"No project", "Нет проекта"}, {"No file", "Нет файла"},
    {"Ln", "Стр"}, {"Col", "Кол"}, {"file(s)", "файлов"},
  };
  const auto translation = russian.find(english);
  return std::string(translation == russian.end() ? english : translation->second);
}

}  // namespace tuiide
